name: Automatic

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  build_and_check:
    if: github.repository == 'alrikn/Zappy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile project
        run: make
        timeout-minutes: 2

      - name: Verify executable
        run: |
          echo "${{ vars.EXECUTABLE }}" | tr -d '\r' | while read -r exe; do
              #now we check if that file exists
              if [ ! -f "$exe" ]; then
                  echo "Executable $exe not found!"
                  exit 1
              fi
          done
          echo "all executables found."

      #- name: Run tests
      #  run: ./raytracer scene_config.cfg -o output.ppm
      #  timeout-minutes: 2 #if it can't be done in 2 minutes, it's bad and something has gone wrong

      - name: Clean
        if: always()
        run: make fclean

  push_to_mirror:
    needs: build_and_check
    if: github.repository == 'alrikn/Zappy' && github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.EPITECH_REPO_SSH }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}